const products = {
    1: {
        name: 'P-51D Mustang',
        category: 'WWII - Caza de Escolta',
        price: 2500000,
        year: 1944,
        motor: 'Packard V-1650-7 Merlin',
        power: '1,490 HP',
        speed: '703 km/h (437 mph)',
        range: '2,755 km (1,712 millas)',
        armament: '6 ametralladoras .50 cal M2',
        wingspan: '11.28 m (37 pies)',
        condition: 'Restaurado - Vuelo',
        description: 'Este excepcional P-51D Mustang representa la cúspide de la aviación de caza de la Segunda Guerra Mundial.',
        image: 'https://i.imgur.com/8Kf8ZqL.jpg'
    },
    2: {
        name: 'F-16C Fighting Falcon',
        category: 'Moderno - Jet',
        price: 18000000,
        year: 1995,
        motor: 'General Electric F110-GE-129',
        power: '29,000 lbf',
        speed: '2,414 km/h (Mach 2+)',
        range: '4,220 km',
        armament: 'Cañón M61 Vulcan + misiles',
        wingspan: '9.96 m',
        condition: 'En servicio activo',
        description: 'Caza polivalente supersónico de 4ta generación.',
        image: 'https://i.imgur.com/jK9mPqW.jpg'
    },
    3: {
        name: 'Supermarine Spitfire Mk IX',
        category: 'WWII - Caza',
        price: 3200000,
        year: 1942,
        motor: 'Rolls-Royce Merlin 61',
        power: '1,565 HP',
        speed: '656 km/h',
        range: '1,827 km',
        armament: '2 cañones de 20mm + 4 ametralladoras',
        wingspan: '11.23 m',
        condition: 'Restaurado - Vuelo',
        description: 'Icono de la Batalla de Inglaterra.',
        image: 'https://i.imgur.com/vN8kR2p.jpg'
    },
    4: {
        name: 'F-22 Raptor',
        category: '5ta Generación',
        price: 150000000,
        year: 2005,
        motor: '2x Pratt & Whitney F119-PW-100',
        power: '35,000 lbf c/u',
        speed: '2,414 km/h (Mach 2.25)',
        range: '2,960 km',
        armament: 'Cañón M61A2 + misiles AIM-120',
        wingspan: '13.56 m',
        condition: 'Stealth - Activo',
        description: 'Caza furtivo de superioridad aérea.',
        image: 'https://i.imgur.com/3TqVx9M.jpg'
    },
    5: {
        name: 'Messerschmitt Bf 109G',
        category: 'WWII - Caza',
        price: 2800000,
        year: 1943,
        motor: 'Daimler-Benz DB 605',
        power: '1,475 HP',
        speed: '640 km/h',
        range: '1,050 km',
        armament: '2 cañones MG 151 + 2 ametralladoras',
        wingspan: '9.92 m',
        condition: 'Restauración museo',
        description: 'Caza alemán icónico de la Luftwaffe.',
        image: 'https://i.imgur.com/wL5hG8T.jpg'
    },
    6: {
        name: 'Sukhoi Su-27 Flanker',
        category: 'Guerra Fría',
        price: 35000000,
        year: 1989,
        motor: '2x Saturn AL-31F',
        power: '27,560 lbf c/u',
        speed: '2,500 km/h (Mach 2.35)',
        range: '3,530 km',
        armament: 'Cañón GSh-30-1 + misiles',
        wingspan: '14.7 m',
        condition: 'Excelente estado',
        description: 'Caza de superioridad aérea soviético.',
        image: 'https://i.imgur.com/2mN9fKp.jpg'
    },
    7: {
        name: 'Mitsubishi A6M Zero',
        category: 'WWII - Caza',
        price: 2100000,
        year: 1941,
        motor: 'Nakajima NK1C Sakae 12',
        power: '950 HP',
        speed: '533 km/h',
        range: '3,104 km',
        armament: '2 cañones de 20mm + 2 ametralladoras',
        wingspan: '12 m',
        condition: 'Restaurado',
        description: 'Caza naval japonés legendario.',
        image: 'https://i.imgur.com/5RqP8nL.jpg'
    },
    8: {
        name: 'F-35B Lightning II',
        category: '5ta Generación',
        price: 120000000,
        year: 2020,
        motor: 'Pratt & Whitney F135',
        power: '43,000 lbf',
        speed: '1,960 km/h (Mach 1.6)',
        range: '2,220 km',
        armament: 'Cañón GAU-22/A + misiles',
        wingspan: '10.7 m',
        condition: 'Despegue vertical - Nuevo',
        description: 'Caza furtivo multirrol con despegue vertical.',
        image: 'https://i.imgur.com/9WqT7hN.jpg'
    },
    9: {
        name: 'F4U Corsair',
        category: 'WWII - Caza',
        price: 2300000,
        year: 1944,
        motor: 'Pratt & Whitney R-2800',
        power: '2,000 HP',
        speed: '717 km/h',
        range: '1,633 km',
        armament: '6 ametralladoras .50 cal',
        wingspan: '12.5 m',
        condition: 'Restaurado - Vuelo',
        description: 'Caza embarcado con alas de gaviota.',
        image: 'https://i.imgur.com/kL3mR9P.jpg'
    }
};